backend:
  name: git-gateway
  branch: main

media_folder: "articles/images"
public_folder: "articles/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
